services:
  flask:
    build: .
    command: python -u app.py
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: language_school
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - ./createtable.sql:/docker-entrypoint-initdb.d/createtable.sql
 